<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>disable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Azure.AI.OpenAI" Version="2.9.0-beta.1" />
    <PackageReference Include="OpenAI" Version="2.9.1" />
    <PackageReference Include="DotNetEnv" Version="3.*" />
    <ProjectReference Include="..\mediatr-dotnet\mediatr\MediatR.csproj" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="10.*" />
    <PackageReference Include="Microsoft.Extensions.Logging" Version="10.*" />
    <PackageReference Include="Microsoft.Extensions.Logging.Console" Version="10.*" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\core-dotnet\core\Core.csproj" />
  </ItemGroup>

</Project>
