// Azure Database for PostgreSQL flexible server + database for shared
// Hangfire storage (api/mvc/worker). Admin login password is generated by
// Bicep (newGuid()), never surfaced as an output — reset in the Portal if
// direct admin access is needed. Apps connect via DB_CONNECTION_STRING
// (Npgsql format) supplied as a GitHub secret after provision.

@description('Name of the PostgreSQL flexible server, e.g. wx1116-prod-postgres.')
param serverName string

@description('Name of the PostgreSQL database, e.g. wx1116-prod-hangfire.')
param databaseName string

param location string

@secure()
@description('PostgreSQL admin login username. Supply via azd env set / --parameters at deploy time.')
param administratorLogin string

@secure()
@description('PostgreSQL admin login password. Generated on each deployment and never output.')
param administratorLoginPassword string = newGuid()

@description('Burstable SKU name. Default Standard_B1ms is enough for Hangfire POC workloads.')
param skuName string = 'Standard_B1ms'

@description('Burstable SKU tier.')
param skuTier string = 'Burstable'

@description('PostgreSQL major version.')
param serverVersion string = '16'

@description('Allocated storage in GiB.')
param storageSizeGB int = 32

resource postgresServer 'Microsoft.DBforPostgreSQL/flexibleServers@2024-08-01' = {
  name: serverName
  location: location
  sku: {
    name: skuName
    tier: skuTier
  }
  properties: {
    version: serverVersion
    administratorLogin: administratorLogin
    administratorLoginPassword: administratorLoginPassword
    storage: {
      storageSizeGB: storageSizeGB
    }
    backup: {
      backupRetentionDays: 7
      geoRedundantBackup: 'Disabled'
    }
    network: {
      publicNetworkAccess: 'Enabled'
    }
    highAvailability: {
      mode: 'Disabled'
    }
  }
}

resource allowAzureServicesFirewallRule 'Microsoft.DBforPostgreSQL/flexibleServers/firewallRules@2024-08-01' = {
  parent: postgresServer
  name: 'AllowAllAzureServices'
  properties: {
    startIpAddress: '0.0.0.0'
    endIpAddress: '0.0.0.0'
  }
}

resource postgresDatabase 'Microsoft.DBforPostgreSQL/flexibleServers/databases@2024-08-01' = {
  parent: postgresServer
  name: databaseName
  properties: {
    charset: 'UTF8'
    collation: 'en_US.utf8'
  }
}

output serverName string = postgresServer.name
output serverFullyQualifiedDomainName string = postgresServer.properties.fullyQualifiedDomainName
output databaseName string = postgresDatabase.name
