// SQL logical server + database. SQL-native admin login only -- no Entra
// admin is registered here. The admin password is generated by Bicep
// itself (newGuid(), re-rolled on every deployment) and never surfaced as
// an output, so nobody -- including whoever runs `azd provision` -- ever
// knows it; if direct SQL-login access is ever actually needed, reset the
// password as a one-time credential in the Azure Portal instead.
//
// IMPORTANT: because there's no Entra admin on this server, nobody can run
// `CREATE USER [...] FROM EXTERNAL PROVIDER` yet -- Azure SQL only allows
// creating "FROM EXTERNAL PROVIDER" (Entra) users over an Entra-authenticated
// connection; the SQL-native admin login cannot do it. Before the contained
// database users for api/mvc/worker's managed identities (see the plan's
// "Per-app identities: SQL & Storage access" section) can be created, set
// an Entra admin manually (Portal or `az sql server ad-admin create`) --
// even temporarily, just long enough to run those CREATE USER statements.

@description('Name of the SQL logical server, e.g. wx1116-prod-sql-server.')
param serverName string

@description('Name of the SQL database, e.g. wx1116-prod-sql-database.')
param databaseName string

param location string

@description('SQL admin login username.')
param administratorLogin string

@secure()
@description('SQL admin login password. Deliberately has no externally-supplied value -- Bicep generates a fresh one on every deployment and it is never output, so nobody needs to know or manage it. Reset it as a one-time credential in the Portal if direct SQL-login access is ever actually needed.')
param administratorLoginPassword string = newGuid()

@description('Database SKU tier/name. Default Standard S0 -- Hangfire\'s schema/indexes likely exceed Basic\'s 5 DTU.')
param databaseSkuName string = 'S0'
param databaseSkuTier string = 'Standard'

@description('Max database size in bytes. Default 2 GiB.')
param maxSizeBytes int = 2147483648

resource sqlServer 'Microsoft.Sql/servers@2023-08-01' = {
  name: serverName
  location: location
  properties: {
    administratorLogin: administratorLogin
    administratorLoginPassword: administratorLoginPassword
    minimalTlsVersion: '1.2'
    publicNetworkAccess: 'Enabled'
  }
}

resource sqlDatabase 'Microsoft.Sql/servers/databases@2023-08-01' = {
  parent: sqlServer
  name: databaseName
  location: location
  sku: {
    name: databaseSkuName
    tier: databaseSkuTier
  }
  properties: {
    maxSizeBytes: maxSizeBytes
  }
}

output serverName string = sqlServer.name
output serverFullyQualifiedDomainName string = sqlServer.properties.fullyQualifiedDomainName
output databaseName string = sqlDatabase.name
