// SQL logical server + database. SQL-native admin login (break-glass only
// -- its password is generated by Bicep itself via newGuid(), re-rolled on
// every deployment and never surfaced as an output, so nobody -- including
// whoever runs `azd provision` -- ever knows it; reset it as a one-time
// credential in the Portal if direct SQL-login access is ever actually
// needed) *and* an Entra admin, which is the GitHub Actions identity
// itself rather than a human -- see infra/main.bicep for why. That
// identity uses its own Entra-authenticated connection to bootstrap the
// contained users for api/mvc/worker's managed identities
// (infra/scripts/create-contained-users.sql, run from the provisioning
// workflow) -- a SQL-native login cannot do this, Azure SQL only allows
// creating "FROM EXTERNAL PROVIDER" users over an Entra-authenticated
// connection.

@description('Name of the SQL logical server, e.g. wx1116-prod-sql-server.')
param serverName string

@description('Name of the SQL database, e.g. wx1116-prod-sql-database.')
param databaseName string

param location string

@secure()
@description('SQL admin login username. Treated as sensitive -- a non-default, non-obvious username is itself part of the security posture here, not just the password.')
param administratorLogin string

@secure()
@description('SQL admin login password. Deliberately has no externally-supplied value -- Bicep generates a fresh one on every deployment and it is never output, so nobody needs to know or manage it. Reset it as a one-time credential in the Portal if direct SQL-login access is ever actually needed.')
param administratorLoginPassword string = newGuid()

@description('Principal ID of the Entra admin (the GitHub Actions managed identity) -- used only to bootstrap the contained users for the SQL-touching apps.')
param entraAdminPrincipalId string

@description('Login/display name of that same Entra admin.')
param entraAdminLoginName string

@description('Database SKU tier/name. Default Standard S0 -- Hangfire\'s schema/indexes likely exceed Basic\'s 5 DTU.')
param databaseSkuName string = 'S0'
param databaseSkuTier string = 'Standard'

@description('Max database size in bytes. Default 2 GiB.')
param maxSizeBytes int = 2147483648

resource sqlServer 'Microsoft.Sql/servers@2023-08-01' = {
  name: serverName
  location: location
  properties: {
    administratorLogin: administratorLogin
    administratorLoginPassword: administratorLoginPassword
    minimalTlsVersion: '1.2'
    publicNetworkAccess: 'Enabled'
  }
}

resource sqlEntraAdmin 'Microsoft.Sql/servers/administrators@2023-08-01' = {
  parent: sqlServer
  name: 'ActiveDirectory'
  properties: {
    administratorType: 'ActiveDirectory'
    login: entraAdminLoginName
    sid: entraAdminPrincipalId
    tenantId: subscription().tenantId
  }
}

// Special-cased firewall rule: 0.0.0.0-0.0.0.0 is not a literal IP, it's
// the documented Azure SQL convention for "allow any Azure-hosted
// resource" (in any subscription, not just this one) -- this is what the
// Portal creates when you check "Allow Azure services and resources to
// access this server". Coarse but necessary for api/mvc/worker to reach
// the database at all today. Individual developer/office IP rules are
// deliberately NOT managed here -- add those manually (Portal/az cli) as
// needed, not through source control: they're personal and change often,
// and Azure's own Activity Log already audits who added/removed one and
// when, which fits that churn better than a git history that would
// otherwise carry personal IPs forever. The real fix for this rule's
// breadth is Private Endpoint + VNet integration, removing public network
// access entirely -- a good candidate for a future hardening pass.
resource allowAzureServicesFirewallRule 'Microsoft.Sql/servers/firewallRules@2023-08-01' = {
  parent: sqlServer
  name: 'AllowAllWindowsAzureIps'
  properties: {
    startIpAddress: '0.0.0.0'
    endIpAddress: '0.0.0.0'
  }
}

resource sqlDatabase 'Microsoft.Sql/servers/databases@2023-08-01' = {
  parent: sqlServer
  name: databaseName
  location: location
  sku: {
    name: databaseSkuName
    tier: databaseSkuTier
  }
  properties: {
    maxSizeBytes: maxSizeBytes
  }
}

output serverName string = sqlServer.name
output serverFullyQualifiedDomainName string = sqlServer.properties.fullyQualifiedDomainName
output databaseName string = sqlDatabase.name
