name: AI 10 Init

on:
  repository_dispatch:
    types: [start_story_with_ai]

jobs:
  vars:
    uses: ./.github/workflows/ai_20_vars.yml
    with:
      story_source: ${{ github.event.client_payload.story_source }}
      story_number: ${{ github.event.client_payload.story_number }}
      story_id: ${{ github.event.client_payload.story_id }}
      story_name: ${{ github.event.client_payload.story_name }}
      story_description: ${{ github.event.client_payload.story_description }}
      story_checklists_json: ${{ toJson(github.event.client_payload.story_checklists) }}
    secrets: inherit

  branch_and_pr:
    needs: [vars]
    permissions:
      contents: write
      pull-requests: write
    strategy:
      fail-fast: false
      matrix:
        target: ${{ fromJson(needs.vars.outputs.targets_json) }}
    uses: ./.github/workflows/ai_30_branch_and_pr.yml
    with:
      ai_target_dev: ${{ matrix.target.ai_target_dev }}
      branch_name: ${{ matrix.target.branch_name }}
      pr_name: ${{ matrix.target.pr_name }}
    secrets: inherit

  run_ai:
    needs: [vars, branch_and_pr]
    permissions:
      contents: write
      pull-requests: write
    strategy:
      fail-fast: false
      matrix:
        target: ${{ fromJson(needs.vars.outputs.targets_json) }}
    uses: ./.github/workflows/ai_50_run.yml
    with:
      ai_target: ${{ matrix.target.ai_target_dev }}
      branch_name: ${{ matrix.target.branch_name }}
      prompt: ${{ matrix.target.prompt_dev }}
    secrets: inherit

  review_ai:
    needs: [vars, run_ai]
    if: ${{ needs.run_ai.result == 'success' }}
    permissions:
      contents: write
      pull-requests: write
    strategy:
      fail-fast: false
      matrix:
        target: ${{ fromJson(needs.vars.outputs.targets_json) }}
    uses: ./.github/workflows/ai_50_run.yml
    with:
      ai_target: ${{ matrix.target.ai_target_review }}
      branch_name: ${{ matrix.target.branch_name }}
      prompt: ${{ matrix.target.prompt_review }}
    secrets: inherit

  callback:
    needs: [vars, run_ai, review_ai]
    if: ${{ always() }}
    uses: ./.github/workflows/ai_90_callback.yml
    with:
      story_source: ${{ github.event.client_payload.story_source }}
      story_id: ${{ github.event.client_payload.story_id }}
      run_status: ${{ needs.run_ai.result == 'success' && needs.review_ai.result || needs.run_ai.result }}
    secrets: inherit